name: Publish to NPM
on:
  release:
    types: [published]

jobs:
  npm-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@5

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true

      - name: Install Node.js
        uses: actions/setup-node@6
        with:
          node-version: "24"
          cache: pnpm
          registry-url: "https://registry.npmjs.org"

      - name: Build package
        run: pnpm run build

      - name: Publish package to npm
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
